version: '3'

services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://Bilalkhan:Pakistan@cluster1.moct8fi.mongodb.net/
      - NODE_ENV=production
    restart: always

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
