name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check Docker and Minikube status
      run: |
        echo "Docker version:"
        docker --version

        echo "Checking Minikube status..."
        if ! minikube status; then
          echo "Starting Minikube..."
          minikube start
        else
          echo "Minikube is already running"
        fi

        echo "Configuring Docker to use Minikube's daemon..."
        eval $(minikube docker-env)

    - name: Build Docker images
      run: |
        echo "Building backend image..."
        cd app/backend
        docker build -t scd_project-backend:latest .

        echo "Building frontend image..."
        cd ../frontend
        docker build -t scd_project-frontend:latest .

    - name: Load images into Minikube
      run: |
        echo "Loading backend image into Minikube..."
        minikube image load scd_project-backend:latest

        echo "Loading frontend image into Minikube..."
        minikube image load scd_project-frontend:latest

        echo "Verifying images in Minikube..."
        minikube image ls | grep scd_project

    - name: Deploy to Kubernetes
      run: |
        echo "Creating namespace..."
        kubectl apply -f k8s/namespace.yaml

        echo "Applying deployments and services..."
        kubectl apply -f k8s/app-deployment.yaml
        kubectl apply -f k8s/app-service.yaml

        echo "Waiting for deployments to be ready..."
        kubectl -n ecommerce-app rollout status deployment/backend
        kubectl -n ecommerce-app rollout status deployment/frontend

    - name: Display service information
      run: |
        echo "Application deployed successfully!"
        echo "Backend service:"
        kubectl -n ecommerce-app get service backend
        echo "Frontend service:"
        kubectl -n ecommerce-app get service frontend

    - name: Get access URL
      run: |
        echo "Access the application at:"
        minikube service frontend -n ecommerce-app --url

    - name: Set up port forwarding for external access
      run: |
        echo "Setting up port forwarding for external access..."
        # Kill any existing port forwarding on port 8090
        pkill -f "kubectl port-forward.*8090" || true

        # Start port forwarding in the background
        nohup kubectl port-forward -n ecommerce-app service/frontend 8090:80 --address 0.0.0.0 > port-forward.log 2>&1 &

        echo "Waiting for port forwarding to start..."
        sleep 5

        echo "Port forwarding is active. You can access the application at:"
        echo "http://$(hostname -I | awk '{print $1}'):8090"
